Task1-get all tasks
Daniel7Ionescu/task-management-system pull request #50
Opened 2023-12-09 21:56 UTC by CezarN88

2023-12-11 17:29 UTC, Daniel7Ionescu commented on src/main/java/com/teamrocket/tms/controllers/UserController.java
> +        List<TaskDTO> tasks = userService.getAllTasksForUser(userId);
Please consider using the project standard for returns

2023-12-11 17:29 UTC, Daniel7Ionescu requested changes
the thing about the return

2023-12-13 17:40 UTC, GabriellaNuca2209 approved these changes
Good job, brother

2023-12-13 17:44 UTC, Daniel7Ionescu approved these changes
looks good to me

2023-12-13 17:44 UTC, merged