Feature 47/assign team leader
Daniel7Ionescu/task-management-system pull request #58
Opened 2023-12-11 08:37 UTC by rhacp

Changed teamLeader to Long(userId) so even if a user changes his details, the teamLead field will still point to the correct user. Added API to assign teamLeader. Added validation for team already having a teamLeader and validation for PM not setting him up as TL.

2023-12-11 17:53 UTC, GabriellaNuca2209 commented on src/main/java/com/teamrocket/tms/services/user/UserServiceImpl.java
> +        leader.setRole(Role.TEAMLEADER);
Maybe we can do something about the case that a junior/medior is assigned as a team leader?

2023-12-11 17:54 UTC, Daniel7Ionescu commented on src/main/java/com/teamrocket/tms/services/user/UserServiceImpl.java
> +        User leader = userRepository.findById(leaderId)
Maybe we should use targetUser?

2023-12-11 18:01 UTC, Daniel7Ionescu commented on src/main/java/com/teamrocket/tms/services/user/UserServiceImpl.java
> +        leader.setRole(Role.TEAMLEADER);
check team before assigning role to user

2023-12-11 18:02 UTC, GabriellaNuca2209 requested changes
Please consider validations before implementing role changes

2023-12-13 09:06 UTC, Daniel7Ionescu approved these changes
Looks good, should have also mentioned that you are commenting out the direct APIs

2023-12-13 15:33 UTC, GabriellaNuca2209 approved these changes

2023-12-13 15:35 UTC, merged